{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Demo for WatchAndHelp Experiment In VirtualEnv\n",
    "##### This is a demo of how to interact with decision making algorithm in WatchAndHelp Experiment In VirtualEnv.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Setup\n",
    "##### The first step is to start a communication with the simulator. Make sure before you run this notebook, that you have downloaded the correct version of the environment for your OS and your drivers and OS is updated to the latest version."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Connected to server\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "e:\\conda\\envs\\vh\\lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "Exception in thread Thread-11 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n"
     ]
    }
   ],
   "source": [
    "from watch_and_help import *\n",
    "from client import *\n",
    "data = {\"environment\": \"WatchAndHelp1\"}\n",
    "make(data)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Random Agent\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Goal: ('milk', 'on', 'table')\n",
      "Available objects: ['BP_SideTable2', 'Floor_400x548', 'Floor_400x549', 'Floor_400x493', 'BP_Milk', 'BP_ThirdPersonCharacter0', 'Floor_400x547', 'BP_Table1', 'Floor_400x546', 'Floor_400x543', 'BP_Table2', 'SM_TableDining13', 'BP_SideTable1']\n",
      "Warning: Required object 'milk' not found in environment!\n",
      "Available objects: {'bp_sidetable1', 'bp_sidetable2', 'floor_400x549', 'floor_400x493', 'floor_400x548', 'bp_table1', 'bp_thirdpersoncharacter0', 'bp_milk', 'floor_400x543', 'floor_400x546', 'floor_400x547', 'sm_tabledining13', 'bp_table2'}\n"
     ]
    }
   ],
   "source": [
    "## 1. Random Agent\n",
    "\n",
    "goal_spec = {\n",
    "    # Format: (subject, relation_type, target): count_needed\n",
    "    #('apple', 'on', 'table'): 1,\n",
    "    ('milk', 'on', 'table'): 1,\n",
    "}\n",
    "env_name = 'WatchAndHelp1'\n",
    "\n",
    "agent = Random_agent(agent_id=0, char_index=0, max_episode_length=100, num_simulation=1000, max_rollout_steps=5, c_init=1.25, c_base=19652, recursive=False, num_samples=1, num_processes=1, comm=None, logging=False, logging_graphs=False, seed=None, env_name=env_name)\n",
    "graph = agent.load_graph_json()\n",
    "filtered_graph = clean_graph(graph, goal_spec, None)\n",
    "#print(\"Filtered graph nodes:\", [node['name'] for node in filtered_graph])\n",
    "for goal_tuple in goal_spec.keys():\n",
    "    print(f\"Goal: {goal_tuple}\")\n",
    "    # Create a single-goal specification dictionary\n",
    "    single_goal_spec = {goal_tuple: goal_spec[goal_tuple]}\n",
    "    agent.run(single_goal_spec)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Oracle Algorithm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-13 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-21 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-23 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "Exception in thread Exception in thread Thread-26 (_handle_eio_message)    Thread-27 (_handle_eio_message):\n",
      "self._target(*self._args, **self._kwargs):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "        self.run()    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "        _threading_Thread_run(self)    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "_threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "        self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)    \n",
      "\n",
      "return handler(*args)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "        self._handle_event(pkt.namespace, pkt.id, pkt.data)    message = json.load(f)\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "        r = self._trigger_event(data[0], namespace, *data[1:])    return loads(fp.read(),\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "        return handler(*args)return _default_decoder.decode(s)\n",
      "    \n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "return handler(*args)  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      "      File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)raise JSONDecodeError(\"Extra data\", s, end)\n",
      "\n",
      "json.decoder.JSONDecodeError      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      ": message = json.load(f)Extra data: line 34 column 2 (char 719)\n",
      "    \n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "return loads(fp.read(),\n",
      "    return loads(fp.read(),  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "        return _default_decoder.decode(s)return _default_decoder.decode(s)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "        raise JSONDecodeError(\"Extra data\", s, end)raise JSONDecodeError(\"Extra data\", s, end)\n",
      "\n",
      "json.decoderjson.decoder..JSONDecodeErrorJSONDecodeError: : Extra data: line 34 column 2 (char 719)Extra data: line 34 column 2 (char 719)\n",
      "\n",
      "Exception in thread Thread-31 (_handle_eio_message):\n",
      "Exception in thread Traceback (most recent call last):\n",
      "Thread-32 (_handle_eio_message)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "_threading_Thread_run(self)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "self._target(*self._args, **self._kwargs)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "self._target(*self._args, **self._kwargs)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)    \n",
      "return handler(*args)  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    message = json.load(f)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return loads(fp.read(),    \n",
      "return _default_decoder.decode(s)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError    : raise JSONDecodeError(\"Extra data\", s, end)Extra data: line 34 column 2 (char 719)\n",
      "\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-36 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-38 (_handle_eio_message):\n",
      "Exception in thread Traceback (most recent call last):\n",
      "Thread-39 (_handle_eio_message)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()    \n",
      "_threading_Thread_run(self)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    _threading_Thread_run(self)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "        self._handle_event(pkt.namespace, pkt.id, pkt.data)self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])    \n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    return handler(*args)    \n",
      "message = json.load(f)  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "return loads(fp.read(),\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.    JSONDecodeErrorraise JSONDecodeError(\"Extra data\", s, end): \n",
      "Extra data: line 34 column 2 (char 719)json.decoder\n",
      ".JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-43 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Exception in thread Thread-45 (_handle_eio_message):\n",
      "    Traceback (most recent call last):\n",
      "self.run()  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "        _threading_Thread_run(self)_threading_Thread_run(self)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "        self._handle_event(pkt.namespace, pkt.id, pkt.data)self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "        r = self._trigger_event(data[0], namespace, *data[1:])r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "      File \"e:\\environment\\client.py\", line 20, in message\n",
      "return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)    \n",
      "message = json.load(f)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),    \n",
      "return loads(fp.read(),  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)    \n",
      "return _default_decoder.decode(s)  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)    \n",
      "raise JSONDecodeError(\"Extra data\", s, end)json.decoder\n",
      ".json.decoderJSONDecodeError.: JSONDecodeErrorExtra data: line 34 column 2 (char 719): \n",
      "Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-50 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-51 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Exception in thread Thread-53 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "        self.run()_threading_Thread_run(self)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "        _threading_Thread_run(self)self._target(*self._args, **self._kwargs)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "        self._handle_event(pkt.namespace, pkt.id, pkt.data)self._target(*self._args, **self._kwargs)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "        r = self._trigger_event(data[0], namespace, *data[1:])self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "        r = self._trigger_event(data[0], namespace, *data[1:])return handler(*args)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "        message = json.load(f)return handler(*args)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "        return loads(fp.read(),message = json.load(f)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "        return _default_decoder.decode(s)return loads(fp.read(),\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "        raise JSONDecodeError(\"Extra data\", s, end)return _default_decoder.decode(s)\n",
      "\n",
      "json.decoder  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      ".JSONDecodeError: Extra data: line 34 column 2 (char 719)    \n",
      "raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-57 (_handle_eio_message)Exception in thread :\n",
      "Thread-58 (_handle_eio_message)Traceback (most recent call last):\n",
      ":\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "        self.run()self.run()\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "        _threading_Thread_run(self)_threading_Thread_run(self)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "        self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "        self._handle_event(pkt.namespace, pkt.id, pkt.data)self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])    \n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)    \n",
      "return handler(*args)  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),    \n",
      "return loads(fp.read(),  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "        return _default_decoder.decode(s)\n",
      "return _default_decoder.decode(s)  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "    json.decoderraise JSONDecodeError(\"Extra data\", s, end).\n",
      "JSONDecodeErrorjson.decoder: .Extra data: line 34 column 2 (char 719)JSONDecodeError\n",
      ": Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-62 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Exception in thread Extra data: line 34 column 2 (char 719)Thread-64 (_handle_eio_message)\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Exception in thread Thread-66 (_handle_eio_message)    :\n",
      "self.run()Traceback (most recent call last):\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()    \n",
      "_threading_Thread_run(self)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    _threading_Thread_run(self)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._target(*self._args, **self._kwargs)    \n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])    \n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "      File \"e:\\environment\\client.py\", line 20, in message\n",
      "return handler(*args)    \n",
      "message = json.load(f)  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    message = json.load(f)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "return loads(fp.read(),\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    return _default_decoder.decode(s)    \n",
      "raise JSONDecodeError(\"Extra data\", s, end)  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-69 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Exception in thread Thread-70 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    _threading_Thread_run(self)    \n",
      "self._target(*self._args, **self._kwargs)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)    \n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "        return handler(*args)message = json.load(f)\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "        message = json.load(f)return loads(fp.read(),\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "        return loads(fp.read(),return _default_decoder.decode(s)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "raise JSONDecodeError(\"Extra data\", s, end)\n",
      "    json.decoderraise JSONDecodeError(\"Extra data\", s, end).\n",
      "JSONDecodeErrorjson.decoder: .Extra data: line 34 column 2 (char 719)JSONDecodeError\n",
      ": Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-133 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-139 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "Exception in thread Thread-142 (_handle_eio_message):\n",
      "    Traceback (most recent call last):\n",
      "_threading_Thread_run(self)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)    \n",
      "self.run()  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "Exception in thread Exception in thread \n",
      "Thread-144 (_handle_eio_message)Thread-145 (_handle_eio_message)      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      ":\n",
      ":\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "_threading_Thread_run(self)self.run()    \n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "self._target(*self._args, **self._kwargs)\n",
      "self.run()\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "_threading_Thread_run(self)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "              File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "return handler(*args)self._handle_event(pkt.namespace, pkt.id, pkt.data)_threading_Thread_run(self)\n",
      "\n",
      "\n",
      "      File \"e:\\environment\\client.py\", line 20, in message\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "self._target(*self._args, **self._kwargs)    \n",
      "        message = json.load(f)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "self._target(*self._args, **self._kwargs)r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "\n",
      "    \n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "              File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)return loads(fp.read(),return handler(*args)\n",
      "    \n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "          File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])return _default_decoder.decode(s)message = json.load(f)\n",
      "\n",
      "    \n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "return handler(*args)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "\n",
      "          File \"e:\\environment\\client.py\", line 20, in message\n",
      "raise JSONDecodeError(\"Extra data\", s, end)    return handler(*args)\n",
      "return loads(fp.read(),    \n",
      "json.decoder\n",
      "message = json.load(f)  File \"e:\\environment\\client.py\", line 20, in message\n",
      ".  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "JSONDecodeError      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    : message = json.load(f)return _default_decoder.decode(s)Extra data: line 34 column 2 (char 719)    \n",
      "\n",
      "\n",
      "return loads(fp.read(),  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return loads(fp.read(),raise JSONDecodeError(\"Extra data\", s, end)    \n",
      "\n",
      "return _default_decoder.decode(s)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "json.decoder\n",
      ".  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "JSONDecodeError    : return _default_decoder.decode(s)    Extra data: line 34 column 2 (char 719)\n",
      "raise JSONDecodeError(\"Extra data\", s, end)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)    \n",
      "raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-148 (_handle_eio_message):\n",
      "Exception in thread Traceback (most recent call last):\n",
      "Thread-149 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()    \n",
      "self.run()  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)    \n",
      "self._target(*self._args, **self._kwargs)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)    \n",
      "return handler(*args)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "        return loads(fp.read(),message = json.load(f)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "return loads(fp.read(),\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder    .return _default_decoder.decode(s)JSONDecodeError\n",
      ":   File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "Extra data: line 34 column 2 (char 719)\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-155 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Exception in thread Thread-157 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Exception in thread self.run()Thread-158 (_handle_eio_message)\n",
      ":\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    Traceback (most recent call last):\n",
      "self.run()  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "_threading_Thread_run(self)    \n",
      "    self.run()  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "_threading_Thread_run(self)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)        \n",
      "_threading_Thread_run(self)self._target(*self._args, **self._kwargs)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)        \n",
      "self._target(*self._args, **self._kwargs)self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])    \n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "        r = self._trigger_event(data[0], namespace, *data[1:])    return handler(*args)\n",
      "message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "        return handler(*args)    message = json.load(f)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "return loads(fp.read(),\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "return loads(fp.read(),    \n",
      "    return _default_decoder.decode(s)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "return loads(fp.read(),\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)return _default_decoder.decode(s)    \n",
      "\n",
      "raise JSONDecodeError(\"Extra data\", s, end)json.decoder  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      ".json.decoder.JSONDecodeErrorJSONDecodeError:     : Extra data: line 34 column 2 (char 719)raise JSONDecodeError(\"Extra data\", s, end)Extra data: line 34 column 2 (char 719)\n",
      "\n",
      "\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-161 (_handle_eio_message):\n",
      "Exception in thread Traceback (most recent call last):\n",
      "Thread-162 (_handle_eio_message)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "        self.run()self.run()\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "        _threading_Thread_run(self)_threading_Thread_run(self)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)    \n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])    \n",
      "return handler(*args)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    return handler(*args)    \n",
      "message = json.load(f)  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),    \n",
      "return loads(fp.read(),  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "    json.decoderraise JSONDecodeError(\"Extra data\", s, end).\n",
      "JSONDecodeErrorjson.decoder: .Extra data: line 34 column 2 (char 719)JSONDecodeError\n",
      ": Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-168 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-169 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "Exception in thread   File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Thread-170 (_handle_eio_message):\n",
      "    Traceback (most recent call last):\n",
      "self.run()  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "_threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    _threading_Thread_run(self)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._target(*self._args, **self._kwargs)    \n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)    \n",
      "return handler(*args)  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    message = json.load(f)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder    .raise JSONDecodeError(\"Extra data\", s, end)JSONDecodeError\n",
      ": json.decoderExtra data: line 34 column 2 (char 719).\n",
      "JSONDecodeError: Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-174 (_handle_eio_message):\n",
      "Exception in thread Traceback (most recent call last):\n",
      "Thread-175 (_handle_eio_message)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "        _threading_Thread_run(self)_threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)    \n",
      "self._target(*self._args, **self._kwargs)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)    \n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])    \n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "        return handler(*args)return handler(*args)\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "        return loads(fp.read(),return loads(fp.read(),\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "        return _default_decoder.decode(s)return _default_decoder.decode(s)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)    \n",
      "raise JSONDecodeError(\"Extra data\", s, end)json.decoder\n",
      ".json.decoderJSONDecodeError.: JSONDecodeErrorExtra data: line 34 column 2 (char 719): \n",
      "Extra data: line 34 column 2 (char 719)\n",
      "Exception in thread Thread-180 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-184 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 14 column 2 (char 251)\n",
      "Exception in thread Thread-187 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "Exception in thread   File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Thread-188 (_handle_eio_message):\n",
      "    Traceback (most recent call last):\n",
      "self.run()  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "        self.run()_threading_Thread_run(self)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)    \n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])    \n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)    \n",
      "return handler(*args)  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return loads(fp.read(),\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    return _default_decoder.decode(s)    \n",
      "raise JSONDecodeError(\"Extra data\", s, end)  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      "json.decoder    .raise JSONDecodeError(\"Extra data\", s, end)JSONDecodeError\n",
      ": json.decoderExtra data: line 14 column 2 (char 251).\n",
      "JSONDecodeError: Extra data: line 14 column 2 (char 251)\n",
      "Exception in thread Thread-197 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-239 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "Exception in thread Thread-240 (_handle_eio_message)Exception in thread :\n",
      "    Thread-241 (_handle_eio_message)Traceback (most recent call last):\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "        self.run()r = self._trigger_event(data[0], namespace, *data[1:])    \n",
      "\n",
      "self.run()  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)return handler(*args)    \n",
      "\n",
      "_threading_Thread_run(self)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    message = json.load(f)\n",
      "          File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "return loads(fp.read(),    \n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "return _default_decoder.decode(s)    \n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder        .return handler(*args)return handler(*args)JSONDecodeError\n",
      "\n",
      ":   File \"e:\\environment\\client.py\", line 20, in message\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "Extra data: line 82 column 2 (char 1816)\n",
      "        message = json.load(f)message = json.load(f)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    return loads(fp.read(),    \n",
      "raise JSONDecodeError(\"Extra data\", s, end)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "json.decoder.JSONDecodeError    : return _default_decoder.decode(s)Extra data: line 82 column 2 (char 1816)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 82 column 2 (char 1816)\n",
      "Exception in thread Thread-246 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "Exception in thread   File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Thread-247 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()    \n",
      "self.run()  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "        _threading_Thread_run(self)_threading_Thread_run(self)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "        self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "        self._handle_event(pkt.namespace, pkt.id, pkt.data)self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "        r = self._trigger_event(data[0], namespace, *data[1:])r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)    \n",
      "return handler(*args)  File \"e:\\environment\\client.py\", line 20, in message\n",
      "\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),    \n",
      "return loads(fp.read(),  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "        return _default_decoder.decode(s)return _default_decoder.decode(s)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "        raise JSONDecodeError(\"Extra data\", s, end)raise JSONDecodeError(\"Extra data\", s, end)\n",
      "\n",
      "json.decoderjson.decoder..JSONDecodeErrorJSONDecodeError: : Extra data: line 82 column 2 (char 1816)Extra data: line 82 column 2 (char 1816)\n",
      "\n",
      "Exception in thread Thread-261 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 26 column 2 (char 500)\n",
      "Exception in thread Exception in thread Thread-266 (_handle_eio_message)Thread-265 (_handle_eio_message):\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()    \n",
      "self.run()  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)    \n",
      "_threading_Thread_run(self)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "        self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "        self._handle_event(pkt.namespace, pkt.id, pkt.data)self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])    \n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "        raise JSONDecodeError(\"Extra data\", s, end)return _default_decoder.decode(s)\n",
      "\n",
      "json.decoder  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      ".JSONDecodeError    : raise JSONDecodeError(\"Extra data\", s, end)Extra data: line 26 column 2 (char 500)\n",
      "\n",
      "json.decoder.JSONDecodeError: Extra data: line 26 column 2 (char 500)\n",
      "Exception in thread Thread-270 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "Exception in thread   File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "Thread-272 (_handle_eio_message)Exception in thread :\n",
      "Thread-274 (_handle_eio_message)    Traceback (most recent call last):\n",
      ":\n",
      "_threading_Thread_run(self)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self.run()    \n",
      "self.run()      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "self._target(*self._args, **self._kwargs)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "_threading_Thread_run(self)    \n",
      "_threading_Thread_run(self)      File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "self._target(*self._args, **self._kwargs)    \n",
      "self._target(*self._args, **self._kwargs)      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    \n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "\n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    \n",
      "return handler(*args)      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "\n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    \n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "message = json.load(f)\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    return loads(fp.read(),    \n",
      "    message = json.load(f)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "return handler(*args)\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "      File \"e:\\environment\\client.py\", line 20, in message\n",
      "return _default_decoder.decode(s)    \n",
      "return loads(fp.read(),      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      "message = json.load(f)  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)return _default_decoder.decode(s)    \n",
      "\n",
      "return loads(fp.read(),json.decoder  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "\n",
      ".  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "JSONDecodeError    : raise JSONDecodeError(\"Extra data\", s, end)    Extra data: line 26 column 2 (char 500)\n",
      "return _default_decoder.decode(s)\n",
      "json.decoder\n",
      ".  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "JSONDecodeError: Extra data: line 26 column 2 (char 500)\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 26 column 2 (char 500)\n",
      "Exception in thread Thread-283 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-312 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-319 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-343 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-356 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-361 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-368 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 340, in decode\n",
      "    raise JSONDecodeError(\"Extra data\", s, end)\n",
      "json.decoder.JSONDecodeError: Extra data: line 54 column 2 (char 1169)\n",
      "Exception in thread Thread-381 (_handle_eio_message)Exception in thread :\n",
      "Thread-382 (_handle_eio_message)Traceback (most recent call last):\n",
      ":\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()    \n",
      "_threading_Thread_run(self)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    _threading_Thread_run(self)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._target(*self._args, **self._kwargs)    \n",
      "self._handle_event(pkt.namespace, pkt.id, pkt.data)  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)    \n",
      "r = self._trigger_event(data[0], namespace, *data[1:])  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "return handler(*args)\n",
      "      File \"e:\\environment\\client.py\", line 20, in message\n",
      "return handler(*args)\n",
      "      File \"e:\\environment\\client.py\", line 20, in message\n",
      "message = json.load(f)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),    \n",
      "return loads(fp.read(),  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "      File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    return _default_decoder.decode(s)obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())    \n",
      "raise JSONDecodeError(\"Expecting value\", s, err.value) from None  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "\n",
      "json.decoder    .raise JSONDecodeError(\"Expecting value\", s, err.value) from NoneJSONDecodeError\n",
      ": json.decoderExpecting value: line 1 column 1 (char 0).\n",
      "JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
      "Exception in thread Thread-395 (_handle_eio_message):\n",
      "Traceback (most recent call last):\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 1016, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\threading.py\", line 953, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 512, in _handle_eio_message\n",
      "    self._handle_event(pkt.namespace, pkt.id, pkt.data)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 386, in _handle_event\n",
      "    r = self._trigger_event(data[0], namespace, *data[1:])\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\site-packages\\socketio\\client.py\", line 434, in _trigger_event\n",
      "    return handler(*args)\n",
      "  File \"e:\\environment\\client.py\", line 20, in message\n",
      "    message = json.load(f)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 293, in load\n",
      "    return loads(fp.read(),\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\__init__.py\", line 346, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 337, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"e:\\conda\\envs\\vh\\lib\\json\\decoder.py\", line 355, in raw_decode\n",
      "    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n",
      "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33msijiehan\u001b[0m (\u001b[33msijiehan-university-of-toronto\u001b[0m). Use \u001b[1m`wandb login --relogin`\u001b[0m to force relogin\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "Tracking run with wandb version 0.18.6"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Run data is saved locally in <code>e:\\environment\\wandb\\run-20241202_122807-wkhpc0tb</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Syncing run <strong><a href='https://wandb.ai/sijiehan-university-of-toronto/oracle-planning/runs/wkhpc0tb' target=\"_blank\">main-execution</a></strong> to <a href='https://wandb.ai/sijiehan-university-of-toronto/oracle-planning' target=\"_blank\">Weights & Biases</a> (<a href='https://wandb.me/developer-guide' target=\"_blank\">docs</a>)<br/>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View project at <a href='https://wandb.ai/sijiehan-university-of-toronto/oracle-planning' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/oracle-planning</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View run at <a href='https://wandb.ai/sijiehan-university-of-toronto/oracle-planning/runs/wkhpc0tb' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/oracle-planning/runs/wkhpc0tb</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Executing goal 1/1: ('milk', 'on', 'table')\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "subgoal: grab_milk\n",
      "Executing action 1/2: {'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Executing action 2/2: {'agent_index': [0], 'task': [6, 232, 0, 0]}\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[2], line 8\u001b[0m\n\u001b[0;32m      5\u001b[0m wandb\u001b[38;5;241m.\u001b[39minit(project\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124moracle-planning\u001b[39m\u001b[38;5;124m\"\u001b[39m, name\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmain-execution\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m      7\u001b[0m \u001b[38;5;66;03m# Execute task and log metrics\u001b[39;00m\n\u001b[1;32m----> 8\u001b[0m metrics \u001b[38;5;241m=\u001b[39m \u001b[43moracle\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexecute_task\u001b[49m\u001b[43m(\u001b[49m\u001b[43mgoal_specification\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m      9\u001b[0m wandb\u001b[38;5;241m.\u001b[39mlog(metrics)\n\u001b[0;32m     10\u001b[0m wandb\u001b[38;5;241m.\u001b[39mfinish()\n",
      "File \u001b[1;32me:\\environment\\watch_and_help.py:819\u001b[0m, in \u001b[0;36mOracle.execute_task\u001b[1;34m(self, goal_specifications)\u001b[0m\n\u001b[0;32m    817\u001b[0m action_sequence \u001b[38;5;241m=\u001b[39m utils\u001b[38;5;241m.\u001b[39msequence(info[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mplan\u001b[39m\u001b[38;5;124m'\u001b[39m])\n\u001b[0;32m    818\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m i, action_dict \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28menumerate\u001b[39m(action_sequence):\n\u001b[1;32m--> 819\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mupdate_graph()\n\u001b[0;32m    820\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mExecuting action \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mi\u001b[38;5;241m+\u001b[39m\u001b[38;5;241m1\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m/\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mlen\u001b[39m(action_sequence)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00maction_dict\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    821\u001b[0m     set_action(action_dict)\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "oracle = Oracle(max_episode_length=100, env_name=\"WatchAndHelp1\")\n",
    "goal_specification = {('milk', 'on', 'table'): 1,}\n",
    "\n",
    "# Optional: Initialize wandb\n",
    "wandb.init(project=\"oracle-planning\", name=\"main-execution\")\n",
    "\n",
    "# Execute task and log metrics\n",
    "metrics = oracle.execute_task(goal_specification)\n",
    "wandb.log(metrics)\n",
    "wandb.finish()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. WatchAndHelp Algorithm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "Tracking run with wandb version 0.18.6"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Run data is saved locally in <code>e:\\environment\\wandb\\run-20241201_111545-gfo4v1ov</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Syncing run <strong><a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/gfo4v1ov' target=\"_blank\">main-execution</a></strong> to <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning' target=\"_blank\">Weights & Biases</a> (<a href='https://wandb.me/developer-guide' target=\"_blank\">docs</a>)<br/>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View project at <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/mcts-planning</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View run at <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/gfo4v1ov' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/gfo4v1ov</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Finishing last run (ID:gfo4v1ov) before initializing another..."
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View run <strong style=\"color:#cdcd00\">main-execution</strong> at: <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/gfo4v1ov' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/gfo4v1ov</a><br/> View project at: <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/mcts-planning</a><br/>Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Find logs at: <code>.\\wandb\\run-20241201_111545-gfo4v1ov\\logs</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Successfully finished last run (ID:gfo4v1ov). Initializing new run:<br/>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Tracking run with wandb version 0.18.6"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Run data is saved locally in <code>e:\\environment\\wandb\\run-20241201_111546-vae3r0z5</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Syncing run <strong><a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/vae3r0z5' target=\"_blank\">worldly-morning-177</a></strong> to <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning' target=\"_blank\">Weights & Biases</a> (<a href='https://wandb.me/developer-guide' target=\"_blank\">docs</a>)<br/>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View project at <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/mcts-planning</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View run at <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/vae3r0z5' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/vae3r0z5</a>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Checking subgoals...\n",
      "subgoals: [['putIn_232.0_235.0', ('milk', 'inside', 'microwave'), 'inside_232.0_235.0']]\n",
      "satisfied: {}\n",
      "unsatisfied: {('milk', 'inside', 'microwave'): 1}\n",
      "subgoals: [['putIn_232.0_235.0', ('milk', 'inside', 'microwave'), 'inside_232.0_235.0']]\n",
      "last_subgoal: None\n",
      "plan: ['agent_0 walk to object_232', 'agent_0 grab object_232', 'agent_0 walk to object_235', 'agent_0 open object_235', 'agent_0 putIn object_232 object_235']\n",
      "Planned actions: ['agent_0 walk to object_232', 'agent_0 grab object_232', 'agent_0 walk to object_235', 'agent_0 open object_235', 'agent_0 putIn object_232 object_235']\n",
      "Subgoals: ['putIn_232.0_235.0']\n",
      "{'agent_index': [0], 'task': [1, 232, 0, 0]}\n",
      "Action 1/5: [1, 232, 0, 0]\n",
      "{'agent_index': [0], 'task': [6, 232, 0, 0]}\n",
      "Action 2/5: [6, 232, 0, 0]\n",
      "{'agent_index': [0], 'task': [1, 235, 0, 0]}\n",
      "Action 3/5: [1, 235, 0, 0]\n",
      "{'agent_index': [0], 'task': [9, 235, 0, 0]}\n",
      "Action 4/5: [9, 235, 0, 0]\n",
      "{'agent_index': [0], 'task': [7, 232, 235, 0]}\n",
      "Action 5/5: [7, 232, 235, 0]\n",
      "0 goals reached out of 1\n",
      "Success rate: 0.0\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "    <style>\n",
       "        .wandb-row {\n",
       "            display: flex;\n",
       "            flex-direction: row;\n",
       "            flex-wrap: wrap;\n",
       "            justify-content: flex-start;\n",
       "            width: 100%;\n",
       "        }\n",
       "        .wandb-col {\n",
       "            display: flex;\n",
       "            flex-direction: column;\n",
       "            flex-basis: 100%;\n",
       "            flex: 1;\n",
       "            padding: 10px;\n",
       "        }\n",
       "    </style>\n",
       "<div class=\"wandb-row\"><div class=\"wandb-col\"><h3>Run history:</h3><br/><table class=\"wandb\"><tr><td>achieved_subgoals</td><td>▁</td></tr><tr><td>success_goals</td><td>▁</td></tr><tr><td>success_rate</td><td>▁</td></tr><tr><td>total_actions</td><td>▁</td></tr><tr><td>total_goals</td><td>▁</td></tr></table><br/></div><div class=\"wandb-col\"><h3>Run summary:</h3><br/><table class=\"wandb\"><tr><td>achieved_subgoals</td><td>1</td></tr><tr><td>success_goals</td><td>0</td></tr><tr><td>success_rate</td><td>0</td></tr><tr><td>total_actions</td><td>5</td></tr><tr><td>total_goals</td><td>1</td></tr></table><br/></div></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       " View run <strong style=\"color:#cdcd00\">worldly-morning-177</strong> at: <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/vae3r0z5' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/mcts-planning/runs/vae3r0z5</a><br/> View project at: <a href='https://wandb.ai/sijiehan-university-of-toronto/mcts-planning' target=\"_blank\">https://wandb.ai/sijiehan-university-of-toronto/mcts-planning</a><br/>Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "Find logs at: <code>.\\wandb\\run-20241201_111546-vae3r0z5\\logs</code>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    " # Initialize wandb\n",
    "wandb.init(\n",
    "    project=\"mcts-planning\",\n",
    "    name=\"main-execution\",\n",
    "    config={\"environment\": \"WatchAndHelp1\"}\n",
    ")\n",
    "\n",
    "# Initialize MCTS\n",
    "mcts = MCTS(\n",
    "    agent_id=0,\n",
    "    max_episode_length=100,\n",
    "    num_simulation=1000,\n",
    "    max_rollout_step=5,\n",
    "    c_init=1.25,\n",
    "    c_base=19652,\n",
    "    env_name=\"WatchAndHelp1\",\n",
    ")\n",
    "\n",
    "# Define goals and run task\n",
    "goal_specification = {\n",
    "    ('milk', 'inside', 'microwave'): 1,\n",
    "}\n",
    "\n",
    "success_rate = mcts.run_mcts_task(goal_specification)\n",
    "\n",
    "wandb.finish()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "vh",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
